// apps/ninjask/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { App } from './app';
import './index.css';

if (import.meta.env.DEV) {
  const { mockWorker } = await import('@/mocks/server/browser');

  await mockWorker.start({ onUnhandledRequest: 'bypass' });
}

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const root = document.getElementById('root')!;

render(() => <App />, root);

// apps/smeargle/src/main.tsx
import { createRoot } from 'react-dom/client';
import { App } from './app/app.tsx';
import './index.css';
import { StrictMode } from 'react';

if (import.meta.env.DEV) {
  const { mockWorker } = await import('@/mocks/server/browser');

  await mockWorker.start({ onUnhandledRequest: 'bypass' });
}

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
