// packages/ui-angular/src/lib/components/example-counter/example-counter.ts
import { Component, signal } from '@angular/core';

/** Only used as placeholder while no other components are created. */
@Component({
  selector: 'natu-example-counter',
  template: `<button type="button" (click)="handleCounterClick()">count is {{ count() }}</button>`,
})
export class ExampleCounter {
  protected readonly count = signal(0);

  protected handleCounterClick() {
    this.count.update((count) => count + 1);
  }
}

// packages/ui-react/src/lib/components/example-counter/example-counter.tsx
import { useState } from 'react';

/** Only used as placeholder while no other components are created. */
export function ExampleCounter() {
  const [count, setCount] = useState(0);

  return (
    <button
      type="button"
      onClick={() => {
        setCount((count) => count + 1);
      }}
    >
      count is {count}
    </button>
  );
}
