// apps/smeargle/src/app/app.tsx
import { Counter } from './components/counter/counter';
import { Header } from './components/header/header';
import { Sidebar } from './components/sidebar/sidebar';
import '../styles/styles.scss';
import styles from './app.module.scss';

export function App() {
  return (
    <div className={styles.root}>
      <Header className={styles.header} />

      <Sidebar className={styles.sidebar} />

      <main className={styles.main}>
        <Counter />
      </main>
    </div>
  );
}

// apps/rotom/src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CounterComponent } from './components/counter/counter.component';
import { HeaderComponent } from './components/header/header.component';
import { SidebarComponent } from './components/sidebar/sidebar.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [CounterComponent, HeaderComponent, SidebarComponent],
})
export class AppComponent {}

<app-header class="app__header" />

<app-sidebar class="app__sidebar" />

<main class="app__main">
  <app-counter />
</main>
